### ISSUE TITLE
crash.  

### ISSUE THREAD

**Issue by ArcticHydra** [Developer-Mike/Autototem-Fabric#5]
I get a crash on would start. 

[21:05:54] [main/INFO]:
 Loading Minecraft 1.20.2 with Fabric Loader 0.14.23
[21:05:55] [ForkJoinPool-1-worker-3/WARN]:
 The mod "autototem" contains invalid entries in its mod json:
- Unsupported root entry "issues" at line 7 column 11
- Unsupported root entry "homepage" at line 8 column 13

Then later
[21:06:31] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.NoSuchMethodError: 'void net.minecraft.class_2817.<init>(net.minecraft.class_2960, net.minecraft.class_2540)'
	at net.minecraft.class_634.handler$zzb000$autototem$sendInfoPackage(class_634.java:3383) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:440) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.14.23.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.23.jar:?]

**Comment by Developer-Mike** [comment]
Thank you for reporting the issue. I'll try to fix it this weekend.

**Comment by Developer-Mike** [comment]
Fixed in version `1.0.3`
