### ISSUE TITLE
Brigadier NullPointerException

### ISSUE THREAD

**Issue by TBhatti90** [Developer-Mike/Autototem-Fabric#8]
Hey just wanted to report this error. I'm using 1.20.2, and using the fabulously optimized modpack and other assorted mods. I can't use the chat / feature. So no /help or /about, etc. Thought I should post it. Those chat features work fine, when the mod is disabled.

`[04:13:44] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:Client uses the Autototem mod.
	at net.minecraft.class_2960.method_45137(class_2960.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10810(class_2540.java:640) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.<init>(class_2817.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.handler$zzg000$autototem$sendInfoPackage(class_634.java:3384) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:440) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
`

`[04:13:44] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "com.mojang.brigadier.CommandDispatcher.getRoot()" because "net.fabricmc.fabric.impl.command.client.ClientCommandInternals.activeDispatcher" is null
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.addCommands(ClientCommandInternals.java:185) ~[fabric-command-api-v2-2.2.16+b1792f7da0-185bca115e22c86f.jar:?]
	at net.minecraft.class_634.handler$zng000$fabric-command-api-v2$onOnCommandTree(class_634.java:6934) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11145(class_634.java:1378) ~[client-intermediary.jar:?]
	at net.minecraft.class_2641.method_11404(class_2641.java:254) ~[client-intermediary.jar:?]
	at net.minecraft.class_2641.method_11054(class_2641.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
`

`[04:13:45] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "com.mojang.brigadier.CommandDispatcher.getRoot()" because "net.fabricmc.fabric.impl.command.client.ClientCommandInternals.activeDispatcher" is null
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.addCommands(ClientCommandInternals.java:185) ~[fabric-command-api-v2-2.2.16+b1792f7da0-185bca115e22c86f.jar:?]
	at net.minecraft.class_634.handler$zng000$fabric-command-api-v2$onOnCommandTree(class_634.java:6934) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11145(class_634.java:1378) ~[client-intermediary.jar:?]
	at net.minecraft.class_2641.method_11404(class_2641.java:254) ~[client-intermediary.jar:?]
	at net.minecraft.class_2641.method_11054(class_2641.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
`

`[04:13:47] [Render thread/WARN]: Error while executing client-sided command 'help'
java.lang.NullPointerException: Cannot invoke "com.mojang.brigadier.CommandDispatcher.execute(String, Object)" because "net.fabricmc.fabric.impl.command.client.ClientCommandInternals.activeDispatcher" is null
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.executeCommand(ClientCommandInternals.java:86) ~[fabric-command-api-v2-2.2.16+b1792f7da0-185bca115e22c86f.jar:?]
	at net.minecraft.class_634.handler$zng000$fabric-command-api-v2$onSendCommand(class_634.java:6946) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_45730(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_44056(class_408.java:249) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_25404(class_408.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1454(class_309.java:406) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:402) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.redirect$ebh000$viafabricplus$redirectSync(class_309.java:5120) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:486) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallback$Container.invoke(GLFWKeyCallback.java:82) ~[lwjgl-glfw-3.3.2.jar:?]
	at dynamic_fps.impl.util.event.InputObserver.onKey(InputObserver.java:54) ~[dynamic-fps-3.3.1+minecraft-1.20.0.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
`

**Comment by ASchneider-GitHub** [comment]
For further context, this is happening to me as well with the following mods in 1.20.2:
- Fabric Loader 0.15.3
- `autototem-1.20.4-1.0.3.jar`
- `fabric-api-0.91.3+1.20.2.jar`
